---
title: "goodBad"
author: "Chase Clark"
date: "October 8, 2018"
github_document:
    html_preview: false
---

```{r}
library(ggplot2)
library(MALDIquant)
library(MALDIquantForeign)
library(scales)
```

```{r include=FALSE}
a <- MALDIquantForeign::importMzMl("data/proteinBad.mzML")
a <- a[c(4,1,5)]

b <- MALDIquantForeign::importMzMl("data/proteinGood.mzML")
b <- b[[3]]

a <- c(b,a)


```



```{r}

counter <- 1
df <- NULL

for(i in seq_along(a)){

df <- rbind(df, cbind.data.frame(mass = a[[i]]@mass,
                  intensity = a[[i]]@intensity,
                  sample = rep(counter, length(a[[i]]@intensity))
           ))
       counter <-  counter + 1
  
}



ggplot(df, aes(x = mass, y =intensity)) +
  geom_line() +
  facet_grid(rows = vars(sample), scales = "free_y") +
  scale_x_continuous(labels = comma) +
  coord_cartesian(xlim = c(3000, 15000)) +
  xlab(expression(italic("m/z"))) +
  ylab("Intensity")





```


```{r}
a <- MALDIquantForeign::importMzMl("data/smBad.mzML")
a <- a[c(2, 3, 4)]

b <- MALDIquantForeign::importMzMl("data/smGood.mzML")
b <- b[[6]]

a <- c(b, a)


```



```{r}

counter <- 1
df <- NULL

for(i in seq_along(a)){

df <- rbind(df, cbind.data.frame(mass = a[[i]]@mass,
                  intensity = a[[i]]@intensity,
                  sample = rep(counter, length(a[[i]]@intensity))
           ))
counter <-  counter + 1
  
}



ggplot(df, aes(x = mass, y = intensity)) +
  geom_line() +
  facet_grid(rows = vars(sample), scales = "free_y") +
  scale_x_continuous(labels = comma) +
  coord_cartesian(xlim = c(1040, 1050)) +
  xlab(expression(italic("m/z"))) +
  ylab("Intensity")





```
